server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        default_type text/html;
        try_files /index.html =404;
    }

    location = /index.html {
        default_type text/html;
        try_files /index.html =404;
    }

    location = /web/index.html {
        default_type text/html;
        try_files /index.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /output/ {
        alias /usr/share/nginx/output/;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
